Update dev requirements
* docutils pinnned at 0.17 because sphinx-rtd-theme doesn't support a bigger version
* pytest-factoryboy pinnned at 2.4.0 because on 2.5.0 we get:

      File "/home/adria/dev/pyenvs/ckan-py3/src/ckan/ckan/tests/pytest_ckan/fixtures.py", line 98, in <module>
        register(factories.Sysadmin, "sysadmin")
      File "/home/adria/dev/pyenvs/ckan-py3/lib/python3.8/site-packages/pytest_factoryboy/fixture.py", line 124, in register
        assert model_name != factory_name, (
    AssertionError: Naming collision for <Sysadmin for <class 'ckan.model.user.User'>>:
       * factory fixture name: sysadmin
       * model fixture name: sysadmin
      Please provide different name for model fixture.
    assert 'sysadmin' != 'sysadmin'