[#4801] Selective loading in plugins toolkit
This took a while to get right because exceptions raised during the
toolkit initialization fail silently and the sympton would be the an
import error later on when trying to import something from the toolkit:

from ckan.plugins.toolkit import get_action

ImportError: cannot import name 'get_action'

TODO: Sort out what gets exposed to extensions in terms of CLI commands