Fixes problem with logs interfering with "ckan datastore set-permissions"
When setting the datastore permissions, before this PR, the logging gets in the way:
```
$ ckan datastore set-permissions | sudo -u postgres psql --set ON_ERROR_STOP=1
You are now connected to database "datastore_test" as user "postgres".
ERROR:  syntax error at or near "2020"
LINE 1: 2020-03-26 17:18:05,311 CRITI [ckan.lib.uploader] Please specify a ckan.storage_path in your config for your uploads
```
You can solve this by adding in `2>/dev/null` however this is a complication for the user, and a breaking change for everyone's automated deployment scripts.

So this PR prevents logging happening when you are running this CLI command.

I thought about not loading the config, however it needs to get the value for `ckan.datastore.write_url` etc.

I thought about letting load_config() run and then removing the loggers it sets up. However by this time it has already done the log.critical message seen above. So I needed to prevent the loggers being setup in the first place with the `setup_logging` option.

--

Whilst in this area, the `2>/dev/null` doesn't work when you specify `-c test-core.ini` to setup for tests:

    $ ckan -c test-core.ini datastore set-permissions 2>/dev/null | sudo -u postgres psql --set ON_ERROR_STOP=1

That is because test-core.ini outputs logs to stdout, not stderr. So in this PR I've fixed that anomaly too (in test-core.ini).