Add and refactor member_create tests, and raise better exception when "id" isn't received
If "id" wasn't received, instead of throwing the seemingly unrelated error:

    AttributeError: 'NoneType' object has no attribute 'id'

We now throw:

    ValidationError: {u'id': u'Missing value'}