feature: Better cache control and enable etag generation with flags
new config:

ckan.cache.expires: was ckan.cache_expires: default 3600
ckan.cache.shared.expires: default 7200
ckan.cache.private.expires: default 60
ckan.cache.public.enabled: was ckan.cache_enabled: default True
ckan.cache.private.enabled: default True
ckan.cache.stale_while_revalidates: default 3600
ckan.cache.stale_if_error: default 7200
ckan.cache.no_transform: default False
ckan.cache_etags: default True

fix:
    ckan.cache_enabled now treated as bool instead of just (if set)
    stop anon session creation unless on 'sensitive' pages, ensure webassets have etag, set sane cache defaults, enable etag which reduces bandwidth costs overall