Make actions' data_dict param optional again
Because of how the wrapped functions returned by `get_action()` params
are defined, you must pass a data_dict value when calling them,
otherwise you get an error:

    E       TypeError: wrapped() missing 1 required positional argument:
'data_dict'

But not all actions require a `data_dict`, eg `status_show`,
`package_list`, etc

This was not an issue on the HTTP API endpoint because the blueprint
always passes a value for `data_dict`, even if it's None, but calling
actions directly from Python will fail:

    toolkit.get_action("package_list")({"ignore_auth": True})

    toolkit.get_action("package_list")()