[#3196] Provide the necessary environment for routers to work
Although each app has its own routing mechanism (Flask and Pylons
(routes)), we still need to be able to generate a URL that is served
by the other application. For instance, when requesting `/dataset`, which
is currently served by Pylons, we call `h.url_for(controller='api',
action='get_api')`. This endpoint is served by Flask, so Pylons won't
know how to generate the URL. We need a wrapper that tries Flask first
and falls back to Pylons (next commit). In order to do that though, the
mappers need to work even if the request is not served by their app.

For Flask routes under requests served by Pylons, we wrap the response
in a `test_request_context`. We don't use an `app_context` because this
causes the following errors:

    RuntimeError: Application was not able to create a URL adapter for
request independent URL generation.

For Pylons routes under requests served by Flask, we set the Routes
configuration directly.