Bump pyyaml to 6.0.1
To fix an installation error caused by pyyaml cython requirement:

    AttributeError: cython_sources

https://github.com/yaml/pyyaml/blob/c42fa3bff1eabdb64763bb1526d9ea1ccb708479/CHANGES#L9
https://github.com/yaml/pyyaml/pull/702